// <auto-generated />
using System;
using LeaveManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeaveManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907071408_leavetype_leaverequest_leavebalance_tables_created")]
    partial class leavetype_leaverequest_leavebalance_tables_created
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeaveManagement.Models.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("LeaveManagement.Models.Entities.Leavebalance", b =>
                {
                    b.Property<int>("leavebalanceid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("leavebalanceid"));

                    b.Property<int>("employeeid")
                        .HasColumnType("int");

                    b.Property<int>("leavetypeid")
                        .HasColumnType("int");

                    b.Property<int>("totaldays")
                        .HasColumnType("int");

                    b.Property<int>("useddays")
                        .HasColumnType("int");

                    b.HasKey("leavebalanceid");

                    b.HasIndex("leavetypeid");

                    b.HasIndex("employeeid", "leavetypeid")
                        .IsUnique();

                    b.ToTable("Leavebalances");
                });

            modelBuilder.Entity("LeaveManagement.Models.Entities.Leaverequest", b =>
                {
                    b.Property<int>("leaverequestid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("leaverequestid"));

                    b.Property<DateTime>("applieddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("approvedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("employeeid")
                        .HasColumnType("int");

                    b.Property<DateTime>("fromdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("leavetypeid")
                        .HasColumnType("int");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("todate")
                        .HasColumnType("datetime2");

                    b.HasKey("leaverequestid");

                    b.HasIndex("employeeid");

                    b.HasIndex("leavetypeid");

                    b.ToTable("Leaverequests");
                });

            modelBuilder.Entity("LeaveManagement.Models.Entities.Leavetype", b =>
                {
                    b.Property<int>("leavetypeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("leavetypeid"));

                    b.Property<string>("leavetypename")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("maximumdays")
                        .HasColumnType("int");

                    b.HasKey("leavetypeid");

                    b.ToTable("Leavetypes");
                });

            modelBuilder.Entity("LeaveManagement.Models.Entities.Leavebalance", b =>
                {
                    b.HasOne("LeaveManagement.Models.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("employeeid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveManagement.Models.Entities.Leavetype", "Leavetype")
                        .WithMany()
                        .HasForeignKey("leavetypeid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Leavetype");
                });

            modelBuilder.Entity("LeaveManagement.Models.Entities.Leaverequest", b =>
                {
                    b.HasOne("LeaveManagement.Models.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("employeeid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeaveManagement.Models.Entities.Leavetype", "Leavetype")
                        .WithMany()
                        .HasForeignKey("leavetypeid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Leavetype");
                });
#pragma warning restore 612, 618
        }
    }
}
